name: Daily Commit - 23f3003594@ds.study.iitm.ac.in

on:
  schedule:
    - cron: "15 6 * * *"  # Runs daily at midnight UTC

  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "23f3003594@ds.study.iitm.ac.in"

      - name: Make a commit
        run: |
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt
          git commit -m "Automated commit on $(date)"
          git push

